Features/query interface
thinknetika/testguru pull request #3
Opened 2024-10-31 07:35 UTC by elbub1979

add all_test class method to test model; add test user instance method user model

2024-10-31 07:38 UTC, elbub1979 commented on app/models/user.rb
> +  end
В будущем, когда будем проходить ассоциации, надо будет использовать has_many through или has-and_belong_to_many

2024-10-31 14:11 UTC, VidgarVii requested changes

2024-10-31 14:11 UTC, VidgarVii commented on app/models/test.rb
> +  def self.all_tests(test_category)
по названию метода можно понять, Что он вернет список всех тестов, а не то что в коде. И к сожалению не то что требуется в ТЗ

2024-10-31 14:11 UTC, VidgarVii commented on app/models/test.rb
> +    where(category: test_category)
прочти внимательно ТЗ, что должен вернуть метод.
Важно! В этом ПР мы не используем фишки ассоциаций.

2024-10-31 14:11 UTC, VidgarVii commented on app/models/user.rb
> +  end
возможно. Но сейчас есть конкретная задача, которую надо решить. Внимательно прочти задание.

2024-10-31 16:42 UTC, elbub1979 commented on app/models/user.rb
> +  end
Тогда так. Но user_id в тестах нет.

2024-10-31 16:43 UTC, elbub1979 commented on app/models/test.rb
>    end
Новый метод )

2024-10-31 16:47 UTC, elbub1979 commented on app/models/test.rb
>    end
Точно не знаю пока, но есть подозрение, что когда ты писал, что без ассоциаций, имел ввиду использование id в (category: category). Потому что сейчас я передаю объект, а там уже магия рельс выдергивает id из объекта категория, и сопоставляет с id в category_id

2024-10-31 16:49 UTC, elbub1979 commented on app/models/user.rb
>    end
Тогда так. Но user_id в тестах нет...

2024-11-01 03:59 UTC, VidgarVii requested changes

2024-11-01 03:59 UTC, VidgarVii commented on .gitignore
> +/identifier.sqlite
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2024-11-01 03:59 UTC, VidgarVii commented on app/models/test.rb
>    end
ТЗ
Создайте метод класса в модели Test, который возвращает отсортированный по убыванию массив названий всех Тестов у которых Категория называется определённым образом (**название категории передается в метод в качестве аргумента**).

2024-11-01 03:59 UTC, VidgarVii commented on app/models/test.rb
>    end
Да во время теста и написание кода надо убрать ассоциации, чтобы они не мешали. Задача научиться самим отправлять запросы в бд

2024-11-01 03:59 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :tests, through: :test_passages
в ТЗ ни чего не сказано про ассоциации. Давай учиться делать только то что требуется по ТЗ. Ассоциации будут потом по уроку и тогда из сделаем правильно. Сейчас тут ошибки и они только замедляют выполнение ТЗ

2024-11-01 03:59 UTC, VidgarVii commented on app/models/user.rb
>    end
тут всё правильно, но надо переписать код без использования ассоциаций.

2024-11-01 03:59 UTC, VidgarVii commented on db/seeds.rb
> +
метод create! умеет принимать массив хещей. Запись делает более красивой и без применения переменная_N

2024-11-01 03:59 UTC, VidgarVii commented on db/seeds.rb
> +test_3 = Test.create(title: 'Тест Психология 1', level: 1, category: category_2, author: user_1)
а тут почему не используется bang! метод как выше?

2024-11-01 14:34 UTC, VidgarVii requested changes

2024-11-01 14:34 UTC, VidgarVii commented on app/models/category.rb
>    validates :title, presence: true # проверка на предмет пустой строки, null валидируется на уровне БД
валидации моделей не валидируются на уровне бд. Валидации буду далее по уроку. Вот тогда и надо будет их добавлять

2024-11-01 14:34 UTC, VidgarVii commented on app/models/test.rb
> +    where(category_id: category_id).order(title: :desc).pluck(:title)
вот теперь на много лучше. Мы попали в ТЗ. А теперь надо вспонить прошлый урок по SQL и решить подобную задачу в 1 запрос. А сейчас их 2. Это очень не оптимально

2024-11-01 14:34 UTC, VidgarVii commented on app/models/test.rb
> +    where(category_id: category_id).order(title: :desc).pluck(:title)
второй момент.
для удобства чтения и редактирования можно переносить зачейненные вызовы вот так:
```ruby
  .where(...)
    .order(...)
    .pluck(...)
```

2024-11-01 14:34 UTC, VidgarVii commented on app/models/test_passage.rb
> +  enum status: {
плохая практика делать то что не требовалось в ТЗ. Тратишь лишнее время. И этот код всё-ровно придется удалить, так как не пригодится

2024-11-01 14:34 UTC, VidgarVii commented on app/models/user.rb
> +  end
так же решение верное, но не оптимальное

2024-11-01 14:34 UTC, VidgarVii commented on db/seeds.rb
> +  { body: 'Вопрос 1 Тест IQ 0 level 0', test_id: find_id.call(Test, :title, tests[0][:title]) },
код должен быть максимально простым и оптимизированным
Сейчас при создании вопросов в бд идут лишние запросы, которые можно было не совершать.
Так же прок в данном сиде только усложняет код.
До этого код с большим кол-вом переменных был на много лучше.

2024-11-02 08:03 UTC, merged